### ISSUE TITLE
Visitor: Checkout

### ISSUE THREAD

**Issue by Philippoes** [CraftAcademy/slow_food_sinatra_nov#13]
As a Visitor.
In order to see my chosen dishes and total price.
I need to checkout.

**Comment by AmberWilkie** [comment]
So this might instead be worded:
```
As a Visitor
in order to get my food
I need to checkout.
```

Our User Stories are meant to describe the actions of the users in them. That is, the context in which a user checks out is that he wants to actually get his food. Total price and pickup time are probably a separate user story.

This story should also be about viewing my confirmation or the like. You have the other two - total price and pickup time - but this one should be just about the checkout has gone through. So a Visitor should maybe see a receipt of some sort or a confirmation message.
