### ISSUE TITLE
TODO: create models with Datamapper

### ISSUE THREAD

**Issue by rmzse** [CraftAcademy/slow_food_sinatra_nov#16]
check: 
• http://datamapper.org/docs/properties.html
• http://datamapper.org/docs/associations.html

**Comment by rmzse** [comment]
@Philippoes and @fredrikfalkman pls do orde, @rmzse, @kriizjones and @blondabambi do dishes

**Comment by Philippoes** [comment]
Cancelled.

**Comment by Philippoes** [comment]
cancelled
