### ISSUE TITLE
Visitor: Add dishes to basket

### ISSUE THREAD

**Issue by Philippoes** [CraftAcademy/slow_food_sinatra_nov#7]
As a Visitor.
In order to place an order.
I need to be able to add dishes to a basket.

**Comment by fredrikfalkman** [comment]
![screen shot 2016-11-28 at 13 32 58](https://cloud.githubusercontent.com/assets/23034586/20668699/7a6e78c2-b570-11e6-993d-e7106ad7d8db.png)

**Comment by rmzse** [comment]
Since we need order items now, we have to complete two tasks before we can move ahead on this issue. HOWEVER, we need to do this while encountering these problems in our tests cycles.

1. we need to update our ER model with the new entity and its properties
2. we need to write a test for the
