### ISSUE TITLE
Lo-Fi:s

### ISSUE THREAD

**Issue by aniansson** [CraftAcademy/slow_food_sinatra_nov#9]

**Comment by fredrikfalkman** [comment]
![screen shot 2016-12-02 at 10 50 21](https://cloud.githubusercontent.com/assets/23034586/20829678/5b3fd6a2-b87d-11e6-9b7e-6f1d2b57d5f5.png)

New: Index = Menu + Add to basket including categories

**Comment by fredrikfalkman** [comment]
/Users/fredrikfalkman/Desktop/Screen Shot 2016-11-28 at 13.32.58.png
Shopping basket

**Comment by fredrikfalkman** [comment]
![screen shot 2016-11-28 at 16 18 19](https://cloud.githubusercontent.com/assets/23034586/20673718/7ca5ad52-b586-11e6-9563-82f446b72105.png)
Shopping cart

**Comment by fredrikfalkman** [comment]
![screen shot 2016-11-28 at 16 25 28](https://cloud.githubusercontent.com/assets/23034586/20673956/515d86c8-b587-11e6-80a5-71c655e9a93d.png)
Order Confirmation

**Comment by AmberWilkie** [comment]
Are these all the lo-fis you need? What does the index page look like? The one with meatballs? What about the restaurant information?

**Comment by fredrikfalkman** [comment]
This is an attempt at an mvp. The index is also the menu/add to basket page.
Would you like us to sketch out a more complete implementation?

**Comment by AmberWilkie** [comment]
Not unless you feel you need one. I was just asking questions to help tease
out any missing information. If what you have drawn is enough to build an
index page, then there's no problem.


*Amber Wilkie*
www.amberwilkie.com
0720.08.27.07 | Instagram <http://www.instagram.com/amberwphoto>
